---
services:
  paper-agent:
    image: harbory/paper-agent:latest
    container_name: paper-agent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      # priority: 
      # ENV VARIABLES -> /config/.env -> .env.example
      # - DATABASE_URL=sqlite:////config/paper_agent.db
      # - OPENAI_API_KEY=sk-your-key-here
      # - ENABLE_AUTO_UPDATE=true
      # - AUTO_UPDATE_TIME=03:00 # UTC, usual release time of arxiv
    volumes:
      - ./data:/config
    ports:
      - 8000:8000
    restart: unless-stopped
